name: Deploy on NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-js:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22
          registry-url: 'https://registry.npmjs.com'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Build everything
        run: |
          pnpm install
          pnpm build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          for package in packages/*; do
            if [ -f "$package/package.json" ]; then
              echo "Publishing $package..."
              cd "$package"

              # Bump version dynamically for alpha releases
              sed -i "s/0.0.0/0.0.0-alpha.${GITHUB_RUN_ID}.${GITHUB_RUN_ATTEMPT}/" "package.json"

              npm publish --provenance --access public || echo "Failed to publish $package"
              cd - > /dev/null
            fi
          done
